name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build release
        run: ./gradlew assembleDebug

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Rename Release Notes
        id: rename-release-notes
        run: |
          echo "Yassir - Muhammad Sayed - Release" > new_release_notes.txt
          echo "::set-output name=new_release_notes::new_release_notes.txt"

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotesFile: ${{ steps.rename-release-notes.outputs.new_release_notes }}
